import { ApiMarket } from '@dydxprotocol/solo';

export const getTestMarkets = (): ApiMarket[] => {
    return [
        {
            id: 0,
            oraclePrice: '173192500000000000000',
            spreadPremium: '0',
            createdAt: '',
            updatedAt: '',
            name: '',
            symbol: '',
            supplyIndex: '',
            borrowIndex: '',
            totalSupplyPar: '',
            totalBorrowPar: '',
            lastIndexUpdateSeconds: '',
            collateralRatio: '',
            marginPremium: '',
            currencyUuid: '',
            currency: {
                uuid: '',
                symbol: '',
                contractAddress: '',
                decimals: 0,
                soloMarket: 0,
                createdAt: '',
                updatedAt: '',
            },
            totalSupplyAPR: '',
            totalBorrowAPR: '',
            totalSupplyAPY: '',
            totalBorrowAPY: '',
            totalSupplyWei: '',
            totalBorrowWei: '',
        },
        {
            id: 1,
            oraclePrice: '985976069960621971',
            spreadPremium: '0',
            createdAt: '',
            updatedAt: '',
            name: '',
            symbol: '',
            supplyIndex: '',
            borrowIndex: '',
            totalSupplyPar: '',
            totalBorrowPar: '',
            lastIndexUpdateSeconds: '',
            collateralRatio: '',
            marginPremium: '',
            currencyUuid: '',
            currency: {
                uuid: '',
                symbol: '',
                contractAddress: '',
                decimals: 0,
                soloMarket: 0,
                createdAt: '',
                updatedAt: '',
            },
            totalSupplyAPR: '',
            totalBorrowAPR: '',
            totalSupplyAPY: '',
            totalBorrowAPY: '',
            totalSupplyWei: '',
            totalBorrowWei: '',
        },
        {
            id: 2,
            oraclePrice: '985976069960621971',
            spreadPremium: '0',
            createdAt: '',
            updatedAt: '',
            name: '',
            symbol: '',
            supplyIndex: '',
            borrowIndex: '',
            totalSupplyPar: '',
            totalBorrowPar: '',
            lastIndexUpdateSeconds: '',
            collateralRatio: '',
            marginPremium: '',
            currencyUuid: '',
            currency: {
                uuid: '',
                symbol: '',
                contractAddress: '',
                decimals: 0,
                soloMarket: 0,
                createdAt: '',
                updatedAt: '',
            },
            totalSupplyAPR: '',
            totalBorrowAPR: '',
            totalSupplyAPY: '',
            totalBorrowAPY: '',
            totalSupplyWei: '',
            totalBorrowWei: '',
        },
    ];
};
